import type { Metadata } from "next";
import "./globals.css";
import { ContextProvider } from "@/app/components/ContextProvider";
import Navigation from "./components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <ContextProvider>
          <Navigation />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
